'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RXLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to first_name={0}&amp;email={1}&amp;username={2}.
        '''</summary>
        Friend ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 97b41c52301f77ce508f55e66d17620e.
        '''</summary>
        Friend ReadOnly Property hash_Comments() As String
            Get
                Return ResourceManager.GetString("hash_Comments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ecd67af449fb6edab7c69a205413bfa7.
        '''</summary>
        Friend ReadOnly Property hash_explore() As String
            Get
                Return ResourceManager.GetString("hash_explore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to f92f56d47dc7a55b606908374b43a314.
        '''</summary>
        Friend ReadOnly Property hash_hashtag() As String
            Get
                Return ResourceManager.GetString("hash_hashtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to e0f59e4a1c8d78d0161873bc2ee7ec44.
        '''</summary>
        Friend ReadOnly Property hash_likes() As String
            Get
                Return ResourceManager.GetString("hash_likes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1d67abddd9b9a9554d64cc05ce1e3ffd.
        '''</summary>
        Friend ReadOnly Property hash_timeline() As String
            Get
                Return ResourceManager.GetString("hash_timeline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;__typename&quot;:&quot;.*?&quot;,&quot;id&quot;:&quot;(.*?)&quot;.
        '''</summary>
        Friend ReadOnly Property Posts() As String
            Get
                Return ResourceManager.GetString("Posts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;__typename&quot;:&quot;.*?&quot;,&quot;id&quot;:&quot;(.*?)&quot;,&quot;e.
        '''</summary>
        Friend ReadOnly Property Postshashtag() As String
            Get
                Return ResourceManager.GetString("Postshashtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763.
        '''</summary>
        Friend ReadOnly Property User_agent() As String
            Get
                Return ResourceManager.GetString("User_agent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;username&quot;:&quot;(.*?)&quot;},&quot;vie.
        '''</summary>
        Friend ReadOnly Property users_comments() As String
            Get
                Return ResourceManager.GetString("users_comments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;id&quot;:&quot;\d+&quot;,&quot;username&quot;:&quot;(.*?)&quot;,&quot;full_name.
        '''</summary>
        Friend ReadOnly Property users_likes() As String
            Get
                Return ResourceManager.GetString("users_likes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
